dic = {'P.E.K.K.A': 173, 
       'Valkyrie': 130, 
       'Elixir Golem': 128, 
       'Golem': 105, 
       'Skeletons': 104, 
       'Bats': 84, 'Zap': 83,
       'Tornado': 77, 
       'Royal Giant': 76, 
       'Miner': 72, 
       'Executioner': 72, 
       'Ice Golem': 69, 
       'Giant': 55, 
       'Freeze': 48, 
       'X-Bow': 46, 
       'Magic Archer': 43, 
       'Baby Dragon': 42, 
       'Barbarian Barrel': 40, 
       'Wall Breakers': 39, 
       'Graveyard': 36, 
       'Bandit': 36, 
       'Mega Knight': 36, 
       'Sparky': 35, 
       'Balloon': 33, 
       'The Log': 33, 
       'Hog Rider': 31, 
       'Electro Wizard': 29, 
       'Mini P.E.K.K.A': 28, 
       'Cannon Cart': 27, 
       'Knight': 27, 'Lumberjack': 26, 'Goblin Cage': 26, 'Guards': 25, 'Musketeer': 25, 'Poison': 24, 'Lava Hound': 24, 'Giant Snowball': 22, 'Ice Spirit': 21, 'Goblin Barrel': 20, 'Prince': 19, 'Fireball': 18, 'Princess': 17, 'Ice Wizard': 16, 'Inferno Dragon': 16, 'Goblin Giant': 16, 'Archers': 15, 'Three Musketeers': 14, 'Goblins': 13, 'Skeleton Army': 13, 'Giant Skeleton': 12, 'Cannon': 11, 'Bomb Tower': 10, 'Dart Goblin': 8, 'Lightning': 6, 'Tesla': 6, 'Royal Hogs': 6, 'Minion Horde': 5, 'Bowler': 5, 'Mortar': 4, 'Heal': 4, 'Night Witch': 3, 'Goblin Gang': 3, 'Mirror': 3, 'Ram Rider': 3, 'Earthquake': 2, 'Spear Goblins': 2, 'Barbarians': 2, 'Dark Prince': 2, 'Fisherman': 2, 'Rascals': 1, 'Goblin Hut': 1, 'Witch': 1, 'Rage': 1, 'Royal Ghost': 1}

print(len(dic))
